export const WHATSAPP_NUMBER = '56928683655'
export const wsp = (msg) =>
  `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`

export const categories = [
  {
    id: 'organico',
    num: 'CATEGORÍA 01',
    label: 'Contenido orgánico',
    title: 'Contenido orgánico — video para redes sociales',
    subtitle: 'TikTok · Instagram Reels · YouTube Shorts · Facebook',
    plans: [
      {
        slug: 'impulso-expres',
        badge: 'ENTRADA',
        name: 'Impulso Exprés',
        price: '$60.000',
        period: 'CLP / mes',
        description: 'Para negocios que quieren probar el video marketing sin un gran compromiso. Ideal para empezar a generar contenido estratégico con resultados medibles desde el primer mes.',
        forWho: 'Emprendedores que recién empiezan en redes sociales y quieren ver resultados rápido sin invertir demasiado.',
        features: [
          '3 videos editados',
          '2 videos por semana',
          'Grabación prof. o material del cliente',
          '1 propuesta de contenido basada en tendencias',
        ],
        msg: 'Hola! Me interesa el plan Impulso Exprés de $60.000 CLP/mes 🎬',
      },
      {
        slug: 'impulso-inicial',
        badge: 'BÁSICO',
        name: 'Impulso Inicial',
        price: '$160.000',
        period: 'CLP / mes',
        description: 'Perfecto para marcas que ya saben que necesitan más contenido pero quieren empezar con una base sólida. Incluye asesoría inicial para definir la estrategia correcta.',
        forWho: 'Negocios con presencia en redes que no están creciendo y quieren una estrategia clara con producción constante.',
        features: [
          '8 videos editados',
          '2 videos por semana',
          'Grabación o material del cliente',
          '1 propuesta de contenido en tendencias',
          'Asesoría inicial incluida',
        ],
        msg: 'Hola! Me interesa el plan Impulso Inicial de $160.000 CLP/mes 🎬',
      },
      {
        slug: 'crecimiento-constante',
        badge: 'MÁS ELEGIDO',
        name: 'Crecimiento Constante',
        price: '$210.000',
        period: 'CLP / mes',
        popular: true,
        description: 'El plan más elegido. Diseñado para marcas que quieren presencia constante en redes con contenido de calidad casi todos los días. Incluye estrategia basada en datos reales.',
        forWho: 'Marcas locales o emprendedores que quieren crecer de forma sostenida en TikTok, Reels y Facebook con contenido diario.',
        features: [
          '14 videos editados',
          '4–5 videos por semana',
          'Adaptado para TikTok, Reels y Facebook',
          'Propuesta basada en tendencias y estadísticas',
          'Asesoría estratégica mensual',
        ],
        msg: 'Hola! Quiero el plan Crecimiento Constante de $210.000 CLP/mes 🎬',
      },
      {
        slug: 'a-tope',
        badge: 'MÁXIMO',
        name: 'A Tope',
        price: '$400.000',
        period: 'CLP / mes',
        description: 'Para marcas que quieren dominar sus redes sociales y también correr anuncios. Producción intensiva con reporte mensual completo y planificación del siguiente mes incluida.',
        forWho: 'Marcas establecidas con presupuesto para invertir fuerte en contenido y que quieren el máximo volumen de producción.',
        features: [
          '20 videos editados',
          '5–6 videos por semana',
          'Todo lo del plan Crecimiento +',
          '10 videos enfocados en Ads incluidos',
          'Reporte mensual con métricas y recomendaciones',
          'Reunión de cierre y planificación del mes siguiente',
        ],
        msg: 'Hola! Me interesa el plan A Tope de $400.000 CLP/mes 🎬',
      },
    ],
  },
  {
    id: 'ads-creativos',
    num: 'CATEGORÍA 02',
    label: 'Meta Ads creativos',
    title: 'Meta Ads — planificación de videos creativos',
    subtitle: 'Videos e imágenes para Facebook · Instagram · WhatsApp',
    plans: [
      {
        slug: 'promo-ads',
        badge: 'PUNTUAL',
        name: 'Promo Ads',
        price: '$50.000',
        period: 'CLP · pago único',
        description: 'Un pack puntual para crear los creativos que necesitas para correr un anuncio. Sin mensualidad, sin compromiso. Ideal para lanzar una promoción específica o probar Meta Ads.',
        forWho: 'Negocios que quieren lanzar su primer anuncio o promocionar un producto puntual sin pagar mensualidad.',
        features: [
          'Investigación de mercado incluida',
          '3 videos y/o imágenes para promocionar',
          'Creativos evergreen (duran sin perder efectividad)',
          'Optimizado para conversión por mensaje (WhatsApp / DM)',
          'Optimizado también para website',
        ],
        msg: 'Hola! Me interesa el plan Promo Ads de $50.000 CLP 📣',
      },
      {
        slug: 'ads-continuo',
        badge: 'MÁS ELEGIDO',
        name: 'Ads Continuo',
        price: '$120.000',
        period: 'CLP / mes',
        popular: true,
        description: 'Para negocios que ya tienen anuncios y quieren creativos frescos cada mes. Los creativos evergreen no pierden efectividad con el tiempo, lo que maximiza el retorno de tu pauta.',
        forWho: 'Emprendedores que ya invierten en pauta y quieren creativos de calidad todos los meses para no quemar las mismas piezas.',
        features: [
          'Investigación de mercado incluida',
          '8 videos y/o imágenes para ads',
          'Creativos evergreen para usar siempre',
          'Test A/B: tráfico frío + retargeting',
          'Optimizado para website y conversión por mensaje',
        ],
        msg: 'Hola! Quiero el plan Ads Continuo de $120.000 CLP/mes 📣',
      },
    ],
  },
  {
    id: 'gestion',
    num: 'CATEGORÍA 03',
    label: 'Gestión de campañas',
    title: 'Meta Ads — gestión completa de campañas',
    subtitle: 'Me encargo de todo: setup, audiencias, optimización y reportes',
    plans: [
      {
        slug: 'gestion-basica',
        badge: 'BÁSICO',
        name: 'Gestión Básica',
        price: '$150.000',
        period: 'CLP / mes · pauta $50K–$150K',
        description: 'Para emprendedores con presupuesto de pauta acotado que quieren delegar completamente la gestión de su campaña y recibir resultados mensuales sin complicarse.',
        forWho: 'Negocios pequeños que quieren empezar a pautar en Meta Ads pero no saben cómo manejarlo.',
        features: [
          'Gestión de 1 campaña activa',
          '3 videos creativos al mes incluidos',
          'Optimización semanal de la campaña',
          'Reporte mensual de métricas',
        ],
        msg: 'Hola! Me interesa el plan Gestión Básica de $150.000 CLP/mes 📊',
      },
      {
        slug: 'gestion-completa',
        badge: 'MÁS ELEGIDO',
        name: 'Gestión Completa',
        price: '$250.000',
        period: 'CLP / mes · pauta +$280K',
        popular: true,
        description: 'El plan más elegido para gestión de campañas. Ideal para negocios que quieren escalar con múltiples campañas activas, creativos constantes y optimización permanente.',
        forWho: 'Marcas con presupuesto de pauta mayor a $280.000 que quieren una gestión profesional y resultados escalables.',
        features: [
          'Hasta 3 campañas activas simultáneas',
          '6 videos y/o imágenes al mes',
          'Test A/B cada 2 semanas',
          'Reporte semanal + reporte mensual',
        ],
        msg: 'Hola! Quiero el plan Gestión Completa de $250.000 CLP/mes 📊',
      },
      {
        slug: 'gestion-premium',
        badge: 'PREMIUM',
        name: 'Gestión Premium',
        price: '$400.000',
        period: 'CLP / mes · pauta +$500K',
        description: 'Para marcas con inversión publicitaria alta que necesitan gestión analítica completa, embudo estructurado de frío a conversión y consultoría estratégica de landing page.',
        forWho: 'Empresas con alto volumen de pauta que necesitan el máximo nivel de gestión, análisis y optimización.',
        features: [
          'Campañas ilimitadas',
          '8 videos y/o imágenes al mes',
          'Embudo completo: frío → interés → conversión',
          'Reporte semanal incluido',
          'Consultoría de landing page',
        ],
        msg: 'Hola! Me interesa el plan Gestión Premium de $400.000 CLP/mes 📊',
      },
    ],
  },
  {
    id: 'combos',
    num: 'CATEGORÍA 04 · TODO EN UNO',
    label: 'Combos',
    title: 'Combos — creativos + gestión Meta Ads',
    subtitle: 'Empieza a vender y yo hago absolutamente todo',
    plans: [
      {
        slug: 'combo-ads-starter',
        badge: 'STARTER',
        name: 'Combo Ads Starter',
        price: '$199.000',
        period: 'CLP / mes',
        description: 'La opción todo en uno para quien quiere empezar desde cero. Incluye creativos Y gestión de campañas, así no tienes que coordinar con nadie más. Yo me encargo de todo.',
        forWho: 'Emprendedores que quieren empezar a vender por Meta Ads sin experiencia previa y sin tener que aprender a manejarlo.',
        features: [
          '3 videos y/o imágenes para Meta Ads',
          'Setup completo de cuenta publicitaria',
          'Gestión de 1 o 2 campañas',
          'Audiencia configurada',
          'Reporte mensual de métricas',
        ],
        msg: 'Hola! Me interesa el Combo Ads Starter de $199.000 CLP/mes 🚀',
      },
      {
        slug: 'combo-ads-pro',
        badge: 'MÁS ELEGIDO',
        name: 'Combo Ads Pro',
        price: '$349.990',
        period: 'CLP / mes',
        popular: true,
        description: 'El combo más elegido. Para marcas que quieren resultados reales con estrategia completa de embudo, creativos frescos cada mes y gestión profesional de campañas. Todo incluido.',
        forWho: 'Negocios que quieren escalar sus ventas por redes sociales con una estrategia integral sin ocupar tiempo en eso.',
        features: [
          '6 videos y/o imágenes para ads',
          'Estrategia de embudo mensual completa',
          'Gestión completa de campañas',
          'Test A/B activo permanentemente',
          'Reporte semanal incluido',
        ],
        msg: 'Hola! Quiero el Combo Ads Pro de $349.990 CLP/mes 🚀',
      },
      {
        slug: 'combo-ads-max',
        badge: 'MÁXIMO',
        name: 'Combo Ads Max',
        price: '$549.990',
        period: 'CLP / mes',
        description: 'El pack completo para marcas con visión de escalar. Producción intensiva de creativos junto a gestión analítica de campañas con Test A/B permanente para maximizar el ROAS.',
        forWho: 'Marcas consolidadas con alto presupuesto que necesitan el máximo volumen de producción y la gestión más completa.',
        features: [
          '10 videos y/o imágenes para ads',
          'Gestión analítica de campañas',
          'Test A/B activo permanentemente',
          'Reporte semanal incluido',
        ],
        msg: 'Hola! Me interesa el Combo Ads Max de $549.990 CLP/mes 🚀',
      },
    ],
  },
  {
    id: 'puntuales',
    num: 'CATEGORÍA 05 · SERVICIOS PUNTUALES',
    label: 'Servicios puntuales',
    title: 'Servicios puntuales — pagos únicos sin mensualidad',
    subtitle: 'Para quienes necesitan algo específico sin comprometerse a un plan mensual',
    plans: [
      {
        slug: 'auditoria-ads',
        badge: null,
        name: 'Auditoría Ads',
        price: '$50.000',
        period: 'CLP · pago único',
        description: '¿Tienes campañas corriendo pero no ves resultados? Reviso tu Ads Manager completo y te entrego un informe PDF con exactamente qué está fallando y cómo arreglarlo paso a paso.',
        forWho: 'Negocios que ya tienen anuncios activos pero no están obteniendo el rendimiento esperado.',
        features: [
          'Revisión completa de tu Ads Manager',
          'Análisis de creativos actuales',
          'Informe PDF con lo que está fallando',
          'Recomendaciones concretas para arreglarlo',
        ],
        msg: 'Hola! Me interesa la Auditoría Ads de $50.000 CLP 🔍',
      },
      {
        slug: 'setup-campana',
        badge: null,
        name: 'Setup Campaña',
        price: '$90.000',
        period: 'CLP · pago único',
        description: 'Empiezas de cero o quieres hacerlo tú mismo después. Te dejo todo configurado correctamente y listo para que solo tengas que activar el anuncio cuando quieras.',
        forWho: 'Quienes quieren configurar su cuenta publicitaria bien desde el principio sin pagar una mensualidad de gestión.',
        features: [
          'Instalación de Pixel de Meta',
          'Configuración de cuenta publicitaria',
          '3 videos y/o imágenes incluidos',
          'Todo listo para que lances tu primer anuncio',
        ],
        msg: 'Hola! Me interesa el Setup Campaña de $90.000 CLP ⚙️',
      },
      {
        slug: 'plan-estrategico-ads',
        badge: null,
        name: 'Plan Estratégico Ads',
        price: '$75.000',
        period: 'CLP · pago único',
        description: 'Antes de gastar en pauta, necesitas un plan. Te entrego la hoja de ruta completa para que sepas exactamente a quién llegarle, con qué creativos y con cuánto presupuesto.',
        forWho: 'Emprendedores que quieren empezar a pautar pero no saben por dónde partir ni cuánto invertir.',
        features: [
          'Análisis de tu negocio y público objetivo',
          'Estructura del embudo completa',
          'Presupuesto sugerido en pauta',
          'Tipos de creativos a producir',
          'Entregado antes de gastar en pauta',
        ],
        msg: 'Hola! Me interesa el Plan Estratégico Ads de $75.000 CLP 📋',
      },
    ],
  },
  {
    id: 'viajes',
    num: 'CATEGORÍA 06 · VIAJES',
    label: 'Viajes',
    title: 'Viajes x el mundo — edición de videos de viaje',
    subtitle: 'Para agencias de turismo, influencers de viaje y marcas de experiencias',
    plans: [
      {
        slug: 'chispa',
        badge: null,
        name: 'Chispa',
        price: '$54.000',
        period: 'CLP / mes',
        description: 'Para agencias de turismo, influencers de viaje o marcas de experiencias que quieren mostrar sus destinos con edición profesional en formato short y también correr anuncios con ese material.',
        forWho: 'Agencias turísticas o creadores de contenido de viaje que quieren empezar a publicar videos editados de forma constante.',
        features: [
          '3 videos cortos editados',
          'Edición de videos de viaje',
          'Promoción de Ads también (evergreen)',
        ],
        msg: 'Hola! Me interesa el plan Chispa de $54.000 CLP/mes ✈️',
      },
      {
        slug: 'arranque',
        badge: 'MÁS ELEGIDO',
        name: 'Arranque',
        price: '$99.000',
        period: 'CLP / mes',
        popular: true,
        description: 'El plan ideal para establecer presencia constante con videos de viaje de calidad. Doble la producción del plan Chispa para mayor impacto en redes y más material para anuncios.',
        forWho: 'Marcas de turismo o influencers de viaje que ya tienen contenido pero quieren aumentar su volumen de publicación y calidad.',
        features: [
          '6 videos editados',
          'Edición de videos de viaje',
          'Promoción de Ads también (evergreen)',
        ],
        msg: 'Hola! Quiero el plan Arranque de $99.000 CLP/mes ✈️',
      },
    ],
  },
]

// Mapa plano para buscar un plan por slug
export const plansBySlug = categories.reduce((acc, cat) => {
  cat.plans.forEach((plan) => {
    acc[plan.slug] = { ...plan, categoryTitle: cat.title, categoryNum: cat.num }
  })
  return acc
}, {})
